"""Kikuchi-line geometry for surface electron diffraction (RHEED).

Kikuchi lines appear in a two-step process: inelastic scattering inside the
crystal creates an isotropic source of electrons, which are subsequently
Bragg-scattered. Their *positions* are pure elastic geometry: each 3D
reciprocal vector ``g`` yields a pair of parallel lines on the screen - the
excess line through the screen projection of ``g`` and the deficient line
through the origin. Both lines run perpendicular to the projection of ``g``
and are separated by ``|g_proj|`` (straight-line / flat-screen
approximation; no hyperbola refinement).

The only inelastic ingredient is the mean inner potential ``V0``: inside
the crystal the electron gains kinetic energy ``V0``, so the internal
wavenumber grows to ``k_eff = sqrt(k0^2 + 0.265*V0)`` (A^-1; PyRHEED
convention, ``V0`` in eV, typical 10-20 eV). This refraction enlarges the
Ewald sphere; lines whose projected reciprocal vector exceeds ``k_eff`` are
not observable and are dropped.

Screen conventions: the (flat) screen passes through the origin and is
perpendicular to the incident direction ``k_in``. The origin is the
position of the transmitted beam.
"""

import numpy as np

from .kinematic import TWO_PI, _as_vector

INNER_POTENTIAL_COEFF = 0.265  # A^-2 per eV, PyRHEED convention


def reciprocal_3d(a1, a2, a3):
    """Return the 3D reciprocal basis vectors of a lattice.

    With the cell volume ``V = a1 . (a2 x a3)``,

    ``b1 = 2 pi (a2 x a3) / V``, ``b2 = 2 pi (a3 x a1) / V``,
    ``b3 = 2 pi (a1 x a2) / V``,

    so that ``a_i . b_j = 2 pi delta_ij``.

    Parameters
    ----------
    a1, a2, a3 : array_like
        Real-space lattice basis vectors, each of shape (3,). For a surface
        calculation ``a1`` and ``a2`` lie in the xy surface plane and ``a3``
        carries the out-of-plane component.

    Returns
    -------
    b1, b2, b3 : ndarray
        Reciprocal basis vectors, each of shape (3,).

    Raises
    ------
    ValueError
        If the three vectors are (nearly) coplanar, i.e. the cell volume
        vanishes.
    """
    a1 = _as_vector(a1, "a1", 3)
    a2 = _as_vector(a2, "a2", 3)
    a3 = _as_vector(a3, "a3", 3)
    volume = float(np.dot(a1, np.cross(a2, a3)))
    scale = np.linalg.norm(a1) * np.linalg.norm(a2) * np.linalg.norm(a3)
    if abs(volume) <= 1e-12 * max(scale, 1.0):
        raise ValueError("lattice vectors must span a non-zero 3D volume")
    factor = TWO_PI / volume
    b1 = factor * np.cross(a2, a3)
    b2 = factor * np.cross(a3, a1)
    b3 = factor * np.cross(a1, a2)
    return b1, b2, b3


def _screen_basis(k_in):
    """Return an orthonormal frame (e1, e2) spanning the plane normal to k_in."""
    khat = k_in / np.linalg.norm(k_in)
    reference = np.array([0.0, 0.0, 1.0])
    if abs(np.dot(khat, reference)) > 0.9:
        reference = np.array([0.0, 1.0, 0.0])
    e1 = reference - np.dot(reference, khat) * khat
    e1 = e1 / np.linalg.norm(e1)
    e2 = np.cross(khat, e1)
    return e1, e2


def kikuchi_lines(b1, b2, b3, k_in, inner_potential_eV=0.0, index_max=None):
    """Return the Kikuchi line pairs generated by the reciprocal vectors g.

    For every ``g = h*b1 + k*b2 + l*b3`` with ``|h|, |k|, |l| <= index_max``
    the reciprocal vector is projected onto the screen plane (through the
    origin, perpendicular to ``k_in``). Reciprocal vectors (anti-)parallel
    to ``k_in`` are skipped because their line pair collapses into a point,
    and vectors with ``|g_proj| > k_eff`` are dropped because they lie
    outside the (refraction-enlarged) Ewald sphere.

    Parameters
    ----------
    b1, b2, b3 : array_like
        3D reciprocal basis vectors, each of shape (3,).
    k_in : array_like
        Incident wave vector of shape (3,); its length is the vacuum
        wavenumber ``k0`` (e.g. ``electron_wavenumber(energy_eV)``).
    inner_potential_eV : float
        Mean inner potential ``V0`` in eV; internal wavenumber becomes
        ``k_eff = sqrt(k0^2 + 0.265*V0)``.
    index_max : int or None
        Rod index bound; defaults to 5.

    Returns
    -------
    result : dict
        Metadata keys ``k0``, ``k_eff``, ``inner_potential_eV``,
        ``index_max`` and ``lines``: a list with two records per visible
        reciprocal vector. Each record carries the rod indices ``h``, ``k``,
        ``l``, the 3D vector ``g_3d``, its screen projection ``g_proj``, the
        line type ``"excess"`` / ``"deficient"``, the 2D screen parameters
        ``point_2d`` / ``normal_2d`` (line: points x with
        ``(x - point_2d) . normal_2d = 0``) and the 3D line anchor
        ``point`` / ``direction`` inside the screen plane.
    """
    b1 = _as_vector(b1, "b1", 3)
    b2 = _as_vector(b2, "b2", 3)
    b3 = _as_vector(b3, "b3", 3)
    k_in = _as_vector(k_in, "k_in", 3)
    k0 = float(np.linalg.norm(k_in))
    if k0 == 0.0:
        raise ValueError("k_in must be a non-zero wave vector")
    khat = k_in / k0
    k_eff = np.sqrt(k0 * k0 + INNER_POTENTIAL_COEFF * inner_potential_eV)
    index_max = 5 if index_max is None else int(index_max)
    e1, e2 = _screen_basis(k_in)

    idx = np.arange(-index_max, index_max + 1)
    h3, k3, l3 = np.meshgrid(idx, idx, idx, indexing="ij")
    flat_h = h3.ravel()
    flat_k = k3.ravel()
    flat_l = l3.ravel()
    g = np.outer(flat_h, b1) + np.outer(flat_k, b2) + np.outer(flat_l, b3)
    g_norm = np.linalg.norm(g, axis=1)
    g_proj = g - np.dot(g, khat)[:, None] * khat[None, :]
    proj_norm = np.linalg.norm(g_proj, axis=1)

    nonzero = (flat_h != 0) | (flat_k != 0) | (flat_l != 0)
    not_parallel = proj_norm > 1e-9 * g_norm
    within_sphere = proj_norm <= k_eff * (1.0 + 1e-12)
    keep = nonzero & not_parallel & within_sphere

    lines = []
    if np.any(keep):
        gs = g[keep]
        gps = g_proj[keep]
        hs = flat_h[keep]
        ks = flat_k[keep]
        ls = flat_l[keep]
        unit = gps / proj_norm[keep][:, None]
        p2d = np.column_stack([np.dot(gps, e1), np.dot(gps, e2)])
        normal_2d = p2d / np.linalg.norm(p2d, axis=1)[:, None]
        direction_3d = np.cross(khat[None, :], unit)
        zero2 = np.zeros(2)
        zero3 = np.zeros(3)
        for i in range(gs.shape[0]):
            common = {
                "h": int(hs[i]),
                "k": int(ks[i]),
                "l": int(ls[i]),
                "g_3d": gs[i],
                "g_proj": gps[i],
                "normal_2d": normal_2d[i],
                "direction": direction_3d[i],
            }
            lines.append(
                {
                    **common,
                    "type": "excess",
                    "point_2d": p2d[i],
                    "point": gps[i],
                }
            )
            lines.append(
                {
                    **common,
                    "type": "deficient",
                    "point_2d": zero2.copy(),
                    "point": zero3.copy(),
                }
            )
    return {
        "k0": float(k0),
        "k_eff": float(k_eff),
        "inner_potential_eV": float(inner_potential_eV),
        "index_max": index_max,
        "lines": lines,
    }
